# Generated by Django 3.0.4 on 2020-03-21 13:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200321_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='leaderUser',
        ),
        migrations.AddField(
            model_name='customuser',
            name='associatedUser',
            field=models.ManyToManyField(blank=True, related_name='_customuser_associatedUser_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
