# Generated by Django 3.0.4 on 2020-03-19 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('begin_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('complete', models.BooleanField(default=False)),
                ('parentUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requiredBeforeCompleteTasks', models.ManyToManyField(related_name='_task_requiredBeforeCompleteTasks_+', to='tasks.Task')),
                ('requiredBeforeStartTasks', models.ManyToManyField(related_name='_task_requiredBeforeStartTasks_+', to='tasks.Task')),
                ('subTasks', models.ManyToManyField(related_name='_task_subTasks_+', to='tasks.Task')),
            ],
        ),
    ]
