# Generated by Django 3.0.4 on 2020-03-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='requiredBeforeCompleteTasks',
            field=models.ManyToManyField(blank=True, null=True, related_name='_task_requiredBeforeCompleteTasks_+', to='tasks.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='requiredBeforeStartTasks',
            field=models.ManyToManyField(blank=True, null=True, related_name='_task_requiredBeforeStartTasks_+', to='tasks.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subTasks',
            field=models.ManyToManyField(blank=True, null=True, related_name='_task_subTasks_+', to='tasks.Task'),
        ),
    ]
