# Generated by Django 3.0.4 on 2020-03-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200319_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='requiredBeforeCompleteTasks',
            field=models.ManyToManyField(blank=True, related_name='_task_requiredBeforeCompleteTasks_+', to='tasks.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='requiredBeforeStartTasks',
            field=models.ManyToManyField(blank=True, related_name='_task_requiredBeforeStartTasks_+', to='tasks.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subTasks',
            field=models.ManyToManyField(blank=True, related_name='_task_subTasks_+', to='tasks.Task'),
        ),
    ]
