# Generated by Django 3.0.4 on 2020-03-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200319_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='begin_date',
            new_name='beginDate',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='begin_time',
            new_name='beginTime',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='end_date',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='end_time',
            new_name='endTime',
        ),
        migrations.AddField(
            model_name='task',
            name='completeData',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
