# Generated by Django 3.0.4 on 2020-03-20 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_auto_20200319_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateStamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('dateType', models.PositiveSmallIntegerField(choices=[(1, 'Start Date'), (2, 'End Date'), (3, 'Completion Date')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='fileAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='beginDate',
        ),
        migrations.RemoveField(
            model_name='task',
            name='beginTime',
        ),
        migrations.RemoveField(
            model_name='task',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='task',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='task',
            name='requiredBeforeCompleteTasks',
        ),
        migrations.RemoveField(
            model_name='task',
            name='requiredBeforeStartTasks',
        ),
        migrations.RemoveField(
            model_name='task',
            name='subTasks',
        ),
        migrations.AddField(
            model_name='task',
            name='relatedTasks',
            field=models.ManyToManyField(blank=True, related_name='_task_relatedTasks_+', to='tasks.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='taskType',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Task'), (2, 'Sub Task')], default=1),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=512)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('files', models.ManyToManyField(blank=True, to='tasks.fileAttachment')),
                ('parentTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
                ('parentUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.ManyToManyField(blank=True, to='tasks.Comment'),
        ),
        migrations.AddField(
            model_name='task',
            name='dateStamps',
            field=models.ManyToManyField(to='tasks.DateStamp'),
        ),
        migrations.AddField(
            model_name='task',
            name='files',
            field=models.ManyToManyField(blank=True, to='tasks.fileAttachment'),
        ),
    ]
