# Generated by Django 3.0.4 on 2020-03-20 20:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20200320_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='dateStamps',
        ),
        migrations.AddField(
            model_name='task',
            name='completeDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 20, 30, 2, 207832, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='files',
            field=models.ManyToManyField(blank=True, to='tasks.FileAttachment'),
        ),
        migrations.AlterField(
            model_name='task',
            name='files',
            field=models.ManyToManyField(blank=True, to='tasks.FileAttachment'),
        ),
        migrations.DeleteModel(
            name='DateStamp',
        ),
    ]
